### ISSUE TITLE
App crashes on rotate to landscape mode

### ISSUE THREAD

**Issue by Che4ter** [Che4ter/platypus-android#3]
When I rotated the screen, the whole app crashes
```
05-22 14:43:17.792 8071-8071/ch.stair.platypus E/AndroidRuntime: FATAL EXCEPTION: main
Process: ch.stair.platypus, PID: 8071
java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.stair.platypus/ch.stair.platypus.presentation.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void ch.stair.platypus.di.components.FeedbackComponent.inject(ch.stair.platypus.presentation.card.CardContentFragment)' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4519)
    at android.app.ActivityThread.-wrap19(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void ch.stair.platypus.di.components.FeedbackComponent.inject(ch.stair.platypus.presentation.card.CardContentFragment)' on a null object reference
    at ch.stair.platypus.presentation.card.CardContentFragment.onCreate(CardContentFragment.java:61)
    at android.support.v4.app.Fragment.performCreate(Fragment.java:2180)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1244)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
    at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2893)
    at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:190)
    at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:353)
    at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
    at ch.stair.platypus.presentation.BaseActivity.onCreate(BaseActivity.java:17)
    at ch.stair.platypus.presentation.MainActivity.onCreate(MainActivity.java:39)
    at android.app.Activity.performCreate(Activity.java:6679)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4519) 
    at android.app.ActivityThread.-wrap19(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6119) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 

```

**Comment by wtjerry** [comment]
Analysis:
When changing the App orientation the following methods on an Activity are called: onPause(), onStop() and finally onDestroy(). After that onCreate() is called on the Fragment without onCreate() on the Activity being called first! This means if we are in onCreate() in a Fragment, we cannot rely on our parent Activity being created. This is backed up by this answer: https://stackoverflow.com/a/23004846.

A potential solution might be to move the Fragments logic currently in onCreate() and onViewCreated() into onActivityCreated() or onStart().

see also:
https://github.com/xxv/android-lifecycle
